### ISSUE TITLE
Callback when clicking on the desktop?

### ISSUE THREAD

**Issue by romaincointepas** [pronebird/NSEventMonitor#5] opened 2017-05-15 18:57 UTC
Not sure if this is doable, but I think it would make sense to call the `.start` callback when clicking on the desktop (where the desktop image is), as this library is used to hide the window used for menubars (and native popover/menubar menus hide when clicking on the desktop).

**Comment by pronebird** [comment] 2017-05-16 11:22
You can run monitor throughout the lifetime of the application and you will always receive clicks outside of application's event loop/process. The only thing, we don't really report any data regarding where user clicked, #4 when implemented will pass basic event related data back to node.js.

```
let eventMonitor = new NSEventMonitor();
  
// start capturing global mouse events
eventMonitor.start((NSEventMask.leftMouseDown | NSEventMask.rightMouseDown), () => {
    // do something
});

let window = new BrowserWindow({ ... });
window.show();
```

**Comment by romaincointepas** [comment] 2017-05-16 11:59
Even when running monitor like you described, I still don't receive clicks when clicking on the desktop/desktop image area.

So for example, in the screenshot below:
- I get clicks when clicking anywhere on the menubar except on the example app tray icon.
- I get clicks when clicking anywhere inside that black terminal window.
- I DO NOT get clicks when clicking anywhere on the desktop image (that water/plants image).

<img width="1243" alt="screen shot 2017-05-16 at 7 53 59 pm" src="https://cloud.githubusercontent.com/assets/797899/26104739/c8c2319a-3a71-11e7-944f-9dce2f05c19b.png">

**Comment by pronebird** [comment] 2017-05-16 12:09
I cannot reproduce that. I can only think of NSEventMonitor being recycled by GC at some point, but that seems unlikely in case if its stored in global scope or captures by window handlers..

Could you please try with the branch I just created https://github.com/pronebird/NSEventMonitor/tree/issue/5

This branch never hides the window and consistency captures clicks from anywhere except application's process.

**Comment by romaincointepas** [comment] 2017-05-16 12:18
Tried your branch, can reproduce:

1. Make sure you have some desktop image showing, then npm start
2. Click on tray icon, window shows and has focus.
3. Click on the desktop image area, no event is fired

*Note that clicking on the desktop image area while window is showing BUT does not have focus will fire an event.*

It's not a GC issue as when clicking back to another app, or in menubar, events are fired correctly.

**Comment by pronebird** [comment] 2017-05-16 12:29
I've recorded a video and will upload it shortly. Once again I cannot reproduce this neither in the app we build that uses NSEventMonitor nor with example I shared with you. 

As far as I am concerned, there is no way `addGlobalMonitorForEvents` does not report global clicks. 

It's possible I have a bug in native code that somehow does not reveal itself on my Mac. In that case I can only think of adding `NSLog(@"Event received %@", event);` in https://github.com/pronebird/NSEventMonitor/blob/master/src/NSEventMonitor.mm#L40 and recompile the extension to get log in console from native extension itself.

**Comment by romaincointepas** [comment] 2017-05-16 12:55
Here is a video recording of the issue happening:
https://dl.dropboxusercontent.com/u/6527061/Kapture%202017-05-16%20at%2020.41.44.mp4

Regarding my system/electron version:
macOS 10.12.4 / electron 1.7.0

When doing NSLog inside the native module, where do you get the logs? I can't find them in Console.app.

**Comment by pronebird** [comment] 2017-05-16 14:31
You should get logs in terminal. Why do you receive those weird errors in terminal when you click around? Do you use original mac or hackintosh?

**Comment by pronebird** [comment] 2017-05-16 14:37
That's how it works for me: https://www.dropbox.com/s/34e9ncutnxfurou/Issue5.mov?dl=0

**Comment by romaincointepas** [comment] 2017-05-16 14:52
I'm on latest Macbook Pro 2016 15" with separated GPU, running latest official OS (nothing specific about it).

Regarding those errors in the terminal, not sure what this is about but [I'm not the only one it seems](https://discuss.atom.io/t/imkinputsession-error/36273/4). I wonder if that could be the cause.

Regarding NSLog, I did `npm i` after adding the line but not getting anything in the terminal though (only the FIRE events, nothing from the NSLog).

And I just found out what triggers the bug, try to hide the desktop icons then try to reproduce again:
`defaults write com.apple.finder CreateDesktop false && killall Finder`

**Comment by pronebird** [comment] 2017-05-16 15:32
After running that command I've got the same problem. It seems that you have to click on some other window for desktop to start receiving clicks again. I am not sure why that is so. 

As I understand the setting you switched in Finder is undocumented and is probably not supported.

This module uses public API to observe global clicks and if it's broken due to undocumented feature in Finder then there is not much I can do about that. Closing as won't fix.

**Closed by pronebird** 2017-05-16 15:32 UTC
